spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rbac?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: 6379
    host: 192.168.44.100
    password: 123321

  thymeleaf:
    cache: false

# 自定义登录账号密码
  security:
    user:
      name: root
      password: 123

#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml #xml文件位置，这是默认查找地址，我们放在resource下，可以不配置。