server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/yuhui/mapper/*.xml
  type-aliases-package: com.yuhui.entity
  # 日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志级别
logging:
  level:
    com.yuhui: debug
